name: Deploy Python API to Azure Web App - market-scraper-api

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install -r api/requirements.txt

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_9A71E3612AF945108B7C2A9A422DBFCB }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_929D80D2FF904DCF92E2AB694DCAB127 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_1863D4A39F094FB38D9CC132D4995656 }}

      - name: Set env variables in Azure
        uses: azure/CLI@v1
        env:
          AZURE_CONNECTION_STRING: ${{ secrets.AZURE_CONNECTION_STRING }}
          CONTAINER_NAME: ${{ secrets.CONTAINER_NAME }}
          BRONZE_LOCATION: ${{ secrets.BRONZE_LOCATION }}
          SILVER_LOCATION: ${{ secrets.SILVER_LOCATION }}
        with:
          inlineScript: |
            az webapp config appsettings set --name market-scraper-api --resource-group etf-stocks --settings \
              AZURE_CONNECTION_STRING="${AZURE_CONNECTION_STRING}" \
              CONTAINER_NAME="${CONTAINER_NAME}" \
              BRONZE_LOCATION="${BRONZE_LOCATION}" \
              SILVER_LOCATION="${SILVER_LOCATION}"

      - name: Deploy directly from api folder
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'market-scraper-api'
          slot-name: 'Production'
          package: 'api'

      - name: Set startup command
        uses: azure/cli@v1
        with:
          inlineScript: |
            az webapp config set --name market-scraper-api --resource-group etf-stocks \
              --startup-file "gunicorn --bind 0.0.0.0 --timeout 600 main:app"
